### ISSUE TITLE
Fusion 360/KLP_Keycaps_Normal.f3z is saddle version 

### ISSUE THREAD

**Issue by zwartemees** [braindefender/KLP-Lame-Keycaps#10]
file Fusion 360/KLP_Keycaps_Normal.f3z contains the saddle version not the normal version.

**Comment by braindefender** [comment]
Sorry for not responding for so long. 

This file contains full edit history so you can just suppress the features, that transforms normal into saddle.

You can also use `update` branch of the repo where all files reorganized and fixed.
