### ISSUE TITLE
Do these fit with choc spacing?

### ISSUE THREAD

**Issue by sljdhl** [braindefender/KLP-Lame-Keycaps#13]
Im about to build a choc spaced corne and wondering if these would fit, or if it needs to be mx spaced

**Comment by zawnk** [comment]
I just printed them and put them on my corax which is choc spaced and they fit just fine. So I'd argue that they fit :)

**Comment by braindefender** [comment]
> if these would fit, or if it needs to be mx spaced

The description literally states that there CHOC version and MX version for different switch spacings.

**Comment by BenRoe** [comment]
The KLP keycaps have the following dimensions:
W: 17.5mm / H: 16.5mm

Choc keycaps have:
W: 17.7mm / H: 16.7mm

Conclusion KLP Lame keycaps fit with a choc spacing layout.
