### ISSUE TITLE
Print settings

### ISSUE THREAD

**Issue by sadtab** [braindefender/KLP-Lame-Keycaps#17]
I'm trying to print these jems in PETG, I cant really find the best angle to print them, could you also include a cura or pusa project file with the optimal angle to print them, I'm wondering how you can possible print the MX version with no support

**Comment by braindefender** [comment]
I don't have any particular project files for FDM, but I think supports are mandatory.
And optimal angle for Choc and MX differs, I suppose. Will try to print some MX's later

**Comment by sadtab** [comment]
I appreciate if you could post some screenshots, I just can't get that perfect angle

**Comment by braindefender** [comment]
But I don't think that is possible to print them entirely without supports...

**Comment by braindefender** [comment]
@sadtab 

UPD: that is possible. Need post-processing, but MX socket is almost perfect and without any supports.

![image](https://github.com/user-attachments/assets/ebd88dee-da37-4d51-97c9-1ca54a430ea0)

[KLP Lame FDM Test.zip](https://github.com/user-attachments/files/18056353/KLP.Lame.FDM.Test.zip)
