### ISSUE TITLE
would you be willing to make a version with mx compatible bottoms?

### ISSUE THREAD

**Issue by Leopere** [braindefender/KLP-Lame-Keycaps#3]
Nothing really more to add than the initial question in the subject line.

**Comment by sqdbruh** [comment]
> Nothing really more to add than the initial question in the subject line.

https://github.com/sqdbruh/KLP-Lame-Keycaps

**Comment by braindefender** [comment]
> Nothing really more to add than the initial question in the subject line.

Repository has been updated. MX Version added.

**Comment by Leopere** [comment]
@braindefender & @sqdbruh, thanks for the level-up you've granted the world.
