### ISSUE TITLE
MX STLs not able to be opened in Cura and Prusa

### ISSUE THREAD

**Issue by stevenschmutz** [braindefender/KLP-Lame-Keycaps#9]
Have downloaded all the MX  STLs and they are not able to be opened in Cura or PrusaSlicer.

**Comment by braindefender** [comment]
I don't know why this is happening. Someone on Reddit also has this problem.
But I don't. Just downloaded all MX models and they can be opened in PrusaSlicer (2.7.2)

**Comment by stevenschmutz** [comment]
Problem solved!  After cloning the repo to my local drive, I can use both Prusa and Cura to slice the STLs.

Seems that downloading the individual files from the GitHub repo was the probelm.
